# Generated by Django 3.2.20 on 2023-09-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='entete',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(blank=True, choices=[('EVENEMENTS', 'EVENEMENTS'), ('PROJETS', 'PROJETS'), ('REALISATIONS', 'REALISATIONS'), ('RENCONTRES', 'RENCONTRES')], max_length=250, null=True),
        ),
    ]
