# Generated by Django 3.2.20 on 2023-09-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230901_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_image',
        ),
        migrations.AlterField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(blank=True, choices=[('REALISATIONS', 'REALISATIONS'), ('EVENEMENTS', 'EVENEMENTS'), ('PROJETS', 'PROJETS'), ('RENCONTRES', 'RENCONTRES')], max_length=250, null=True),
        ),
    ]
