# Generated by Django 3.2.20 on 2023-09-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230907_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(blank=True, choices=[('REALISATIONS', 'REALISATIONS'), ('RENCONTRES', 'RENCONTRES'), ('PROJETS', 'PROJETS'), ('EVENEMENTS', 'EVENEMENTS')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='content',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
