# Generated by Django 3.2.20 on 2023-09-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230912_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(blank=True, choices=[('EVENEMENTS', 'EVENEMENTS'), ('RENCONTRES', 'RENCONTRES'), ('PROJETS', 'PROJETS'), ('REALISATIONS', 'REALISATIONS')], max_length=250, null=True),
        ),
    ]
