# Generated by Django 3.2.20 on 2023-09-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_galerie_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(blank=True, choices=[('PROJETS', 'PROJETS'), ('REALISATIONS', 'REALISATIONS'), ('EVENEMENTS', 'EVENEMENTS'), ('RENCONTRES', 'RENCONTRES')], max_length=250, null=True),
        ),
    ]
