# Generated by Django 3.2.20 on 2023-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_galerie_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(blank=True, choices=[('REALISATIONS', 'REALISATIONS'), ('PROJETS', 'PROJETS'), ('RENCONTRES', 'RENCONTRES'), ('EVENEMENTS', 'EVENEMENTS')], max_length=250, null=True),
        ),
    ]
