# Generated by Django 3.2.20 on 2023-09-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230917_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom', models.CharField(blank=True, max_length=250, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=250, null=True)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(blank=True, choices=[('PROJETS', 'PROJETS'), ('EVENEMENTS', 'EVENEMENTS'), ('RENCONTRES', 'RENCONTRES'), ('REALISATIONS', 'REALISATIONS')], max_length=250, null=True),
        ),
    ]
