# Generated by Django 3.2.20 on 2023-09-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230918_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(blank=True, choices=[('PROJETS', 'PROJETS'), ('RENCONTRES', 'RENCONTRES'), ('REALISATIONS', 'REALISATIONS'), ('EVENEMENTS', 'EVENEMENTS')], max_length=250, null=True),
        ),
    ]
