# Generated by Django 3.2.20 on 2023-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_galerie_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(blank=True, choices=[('EVENEMENTS', 'EVENEMENTS'), ('RENCONTRES', 'RENCONTRES'), ('REALISATIONS', 'REALISATIONS'), ('PROJETS', 'PROJETS')], max_length=250, null=True),
        ),
    ]
